# Generated by Django 5.1.3 on 2025-03-24 15:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rentme', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Property',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('property_type', models.CharField(choices=[('pg', 'PG'), ('room', 'Room')], max_length=4)),
                ('location', models.CharField(max_length=255)),
                ('rent', models.DecimalField(decimal_places=2, max_digits=10)),
                ('availability', models.CharField(max_length=100)),
                ('details', models.TextField(blank=True, max_length=500)),
                ('image1', models.ImageField(blank=True, null=True, upload_to='property_images/')),
                ('image2', models.ImageField(blank=True, null=True, upload_to='property_images/')),
                ('image3', models.ImageField(blank=True, null=True, upload_to='property_images/')),
                ('pg_name', models.CharField(blank=True, max_length=100)),
                ('pg_room_type', models.CharField(blank=True, max_length=20)),
                ('pg_capacity', models.PositiveIntegerField(blank=True, null=True)),
                ('pg_wifi', models.BooleanField(default=False)),
                ('pg_meals', models.BooleanField(default=False)),
                ('pg_ac', models.BooleanField(default=False)),
                ('pg_laundry', models.BooleanField(default=False)),
                ('pg_security', models.BooleanField(default=False)),
                ('pg_power', models.BooleanField(default=False)),
                ('pg_parking', models.BooleanField(default=False)),
                ('pg_meal_type', models.CharField(blank=True, max_length=20)),
                ('pg_tenants', models.CharField(blank=True, max_length=20)),
                ('room_title', models.CharField(blank=True, max_length=100)),
                ('room_size', models.CharField(blank=True, max_length=20)),
                ('room_floor', models.PositiveIntegerField(blank=True, null=True)),
                ('room_bathroom', models.BooleanField(default=False)),
                ('room_balcony', models.BooleanField(default=False)),
                ('room_furnished', models.BooleanField(default=False)),
                ('room_kitchen', models.BooleanField(default=False)),
                ('room_light', models.BooleanField(default=False)),
                ('room_wardrobe', models.BooleanField(default=False)),
                ('room_parking', models.BooleanField(default=False)),
                ('room_bathroom_type', models.CharField(blank=True, max_length=20)),
                ('room_tenants', models.CharField(blank=True, max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('seller', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='properties', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
